from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class FinancialEntities(BaseModel):
    """Schema for extracted financial entities from annual reports."""

    company_name: Optional[str] = Field(default=None, alias="Company Name")
    financial_year: Optional[str] = Field(default=None, alias="Financial Year")
    revenue_from_operations: Optional[str] = Field(default=None, alias="Revenue from operations")
    other_income: Optional[str] = Field(default=None, alias="Other income")
    total_income: Optional[str] = Field(default=None, alias="Total Income")
    cost_of_materials_consumed: Optional[str] = Field(default=None, alias="Cost of materials consumed")
    purchases_of_stock_in_trade: Optional[str] = Field(default=None, alias="Purchases of Stock-in-Trade")
    changes_in_inventories: Optional[str] = Field(default=None, alias="Changes in inventories")
    employee_benefits_expense: Optional[str] = Field(default=None, alias="Employee benefits expense")
    finance_costs: Optional[str] = Field(default=None, alias="Finance costs")
    depreciation_and_amortisation_expense: Optional[str] = Field(default=None, alias="Depreciation and amortisation expense")
    other_expenses: Optional[str] = Field(default=None, alias="Other expenses")
    total_expenses: Optional[str] = Field(default=None, alias="Total expenses")
    profit_before_tax: Optional[str] = Field(default=None, alias="Profit before tax")
    current_tax: Optional[str] = Field(default=None, alias="Current tax")
    deferred_tax: Optional[str] = Field(default=None, alias="Deferred tax")
    profit_after_tax: Optional[str] = Field(default=None, alias="Profit after tax")
    ebit: Optional[str] = Field(default=None, alias="EBIT")
    ebitda: Optional[str] = Field(default=None, alias="EBITDA")

    total_assets: Optional[str] = Field(default=None, alias="Total Assets")
    total_liabilities: Optional[str] = Field(default=None, alias="Total Liabilities")
    total_equity: Optional[str] = Field(default=None, alias="Total Equity")
    cash_and_cash_equivalents: Optional[str] = Field(default=None, alias="Cash and cash equivalents")
    borrowings: Optional[str] = Field(default=None, alias="Borrowings")
    trade_receivables: Optional[str] = Field(default=None, alias="Trade receivables")
    trade_payables: Optional[str] = Field(default=None, alias="Trade payables")
    inventories: Optional[str] = Field(default=None, alias="Inventories")
    property_plant_equipment: Optional[str] = Field(default=None, alias="Property Plant Equipment")
    capital_work_in_progress: Optional[str] = Field(default=None, alias="Capital work in progress")
    investment_property: Optional[str] = Field(default=None, alias="Investment Property")
    goodwill: Optional[str] = Field(default=None, alias="Goodwill")
    other_intangible_assets: Optional[str] = Field(default=None, alias="Other Intangible Assets")
    investments: Optional[str] = Field(default=None, alias="Investments")
    loans: Optional[str] = Field(default=None, alias="Loans")
    deferred_tax_assets: Optional[str] = Field(default=None, alias="Deferred Tax Assets")
    deferred_tax_liabilities: Optional[str] = Field(default=None, alias="Deferred Tax Liabilities")
    current_assets: Optional[str] = Field(default=None, alias="Current Assets")
    non_current_assets: Optional[str] = Field(default=None, alias="Non Current Assets")
    current_liabilities: Optional[str] = Field(default=None, alias="Current Liabilities")
    non_current_liabilities: Optional[str] = Field(default=None, alias="Non Current Liabilities")

    non_current_assets_detail: Optional[str] = Field(default=None, alias="Non-current assets")
    property_plant_and_equipment: Optional[str] = Field(default=None, alias="Property Plant and Equipment")
    capital_work_in_progress_detail: Optional[str] = Field(default=None, alias="Capital work-in-progress")
    investment_property_detail: Optional[str] = Field(default=None, alias="Investment Property")
    goodwill_detail: Optional[str] = Field(default=None, alias="Goodwill")
    other_intangible_assets_detail: Optional[str] = Field(default=None, alias="Other Intangible Assets")
    intangible_assets_under_development: Optional[str] = Field(default=None, alias="Intangible Assets Under Development")
    biological_assets: Optional[str] = Field(default=None, alias="Biological Assets")
    financial_assets: Optional[str] = Field(default=None, alias="Financial Assets")
    investments_detail: Optional[str] = Field(default=None, alias="Investments")
    trade_receivables_detail: Optional[str] = Field(default=None, alias="Trade Receivables")
    loans_detail: Optional[str] = Field(default=None, alias="Loans")
    deferred_tax_assets_detail: Optional[str] = Field(default=None, alias="Deferred Tax Assets")
    other_non_current_assets: Optional[str] = Field(default=None, alias="Other Non Current Assets")
    total_non_current_assets: Optional[str] = Field(default=None, alias="Total Non Current Assets")
    total_fixed_assets: Optional[str] = Field(default=None, alias="Total Fixed Assets")

    current_assets_detail: Optional[str] = Field(default=None, alias="Current Assets")
    inventories_detail: Optional[str] = Field(default=None, alias="Inventories")
    current_investments: Optional[str] = Field(default=None, alias="Current Investments")
    trade_receivables_current: Optional[str] = Field(default=None, alias="Trade Receivables")
    cash_and_cash_equivalents_detail: Optional[str] = Field(default=None, alias="Cash and Cash Equivalents")
    bank_balances: Optional[str] = Field(default=None, alias="Bank Balances")
    loans_current: Optional[str] = Field(default=None, alias="Loans")
    other_financial_assets: Optional[str] = Field(default=None, alias="Other Financial Assets")
    current_tax_assets: Optional[str] = Field(default=None, alias="Current Tax Assets")
    other_current_assets: Optional[str] = Field(default=None, alias="Other Current Assets")
    total_current_assets: Optional[str] = Field(default=None, alias="Total Current Assets")

    equity_share_capital: Optional[str] = Field(default=None, alias="Equity Share Capital")
    other_equity: Optional[str] = Field(default=None, alias="Other Equity")
    total_equity_detail: Optional[str] = Field(default=None, alias="Total Equity")
    profit_for_the_year: Optional[str] = Field(default=None, alias="Profit for the Year")
    change_in_fctr: Optional[str] = Field(default=None, alias="Change in FCTR")
    nci_share_of_loss: Optional[str] = Field(default=None, alias="NCI Share of Loss")

    non_current_liabilities_detail: Optional[str] = Field(default=None, alias="Non Current Liabilities")
    borrowings_detail: Optional[str] = Field(default=None, alias="Borrowings")
    trade_payables_detail: Optional[str] = Field(default=None, alias="Trade Payables")
    other_financial_liabilities: Optional[str] = Field(default=None, alias="Other Financial Liabilities")
    provisions: Optional[str] = Field(default=None, alias="Provisions")
    deferred_tax_liabilities_detail: Optional[str] = Field(default=None, alias="Deferred Tax Liabilities")
    other_non_current_liabilities: Optional[str] = Field(default=None, alias="Other Non Current Liabilities")
    total_non_current_liabilities: Optional[str] = Field(default=None, alias="Total Non Current Liabilities")

    current_liabilities_detail: Optional[str] = Field(default=None, alias="Current Liabilities")
    borrowings_current: Optional[str] = Field(default=None, alias="Borrowings")
    trade_payables_current: Optional[str] = Field(default=None, alias="Trade Payables")
    other_financial_liabilities_current: Optional[str] = Field(default=None, alias="Other Financial Liabilities")
    other_current_liabilities: Optional[str] = Field(default=None, alias="Other Current Liabilities")
    current_provisions: Optional[str] = Field(default=None, alias="Current Provisions")
    current_tax_liabilities: Optional[str] = Field(default=None, alias="Current Tax Liabilities")
    total_current_liabilities: Optional[str] = Field(default=None, alias="Total Current Liabilities")

    total_liabilities_detail: Optional[str] = Field(default=None, alias="Total Liabilities")
    total_equity_and_liabilities: Optional[str] = Field(default=None, alias="Total Equity and Liabilities")
    total_debt: Optional[str] = Field(default=None, alias="Total Debt")

    revenue_from_operations_detail: Optional[str] = Field(default=None, alias="Revenue from Operations")
    other_income_detail: Optional[str] = Field(default=None, alias="Other Income")
    total_income_detail: Optional[str] = Field(default=None, alias="Total Income")
    current_tax_detail: Optional[str] = Field(default=None, alias="Current Tax")
    deferred_tax_detail: Optional[str] = Field(default=None, alias="Deferred Tax")
    tax_expense: Optional[str] = Field(default=None, alias="Tax Expense")
    profit_for_the_year_detail: Optional[str] = Field(default=None, alias="Profit for the Year")
    profit_after_tax_detail: Optional[str] = Field(default=None, alias="Profit After Tax")
    profit_before_tax_detail: Optional[str] = Field(default=None, alias="Profit Before Tax")
    profit_before_exceptional_items: Optional[str] = Field(default=None, alias="Profit Before Exceptional Items")
    exceptional_items: Optional[str] = Field(default=None, alias="Exceptional Items")
    cost_of_materials_consumed_detail: Optional[str] = Field(default=None, alias="Cost of Materials Consumed")
    purchases_detail: Optional[str] = Field(default=None, alias="Purchases")
    inventory_changes: Optional[str] = Field(default=None, alias="Inventory Changes")
    employee_benefits: Optional[str] = Field(default=None, alias="Employee Benefits")
    finance_costs_detail: Optional[str] = Field(default=None, alias="Finance Costs")
    depreciation_detail: Optional[str] = Field(default=None, alias="Depreciation")
    other_expenses_detail: Optional[str] = Field(default=None, alias="Other Expenses")
    total_expenses_detail: Optional[str] = Field(default=None, alias="Total Expenses")
    ebitda_detail: Optional[str] = Field(default=None, alias="EBITDA")
    ebit_detail: Optional[str] = Field(default=None, alias="EBIT")

    operating_cash_flow: Optional[str] = Field(default=None, alias="Operating Cash Flow")
    investing_cash_flow: Optional[str] = Field(default=None, alias="Investing Cash Flow")
    financing_cash_flow: Optional[str] = Field(default=None, alias="Financing Cash Flow")
    cash_flow_from_operating_activities: Optional[str] = Field(default=None, alias="Cash Flow from Operating Activities")
    cash_flow_from_investing_activities: Optional[str] = Field(default=None, alias="Cash Flow from Investing Activities")
    cash_flow_from_financing_activities: Optional[str] = Field(default=None, alias="Cash Flow from Financing Activities")
    net_increase_in_cash: Optional[str] = Field(default=None, alias="Net Increase in Cash")
    closing_cash_balance: Optional[str] = Field(default=None, alias="Closing Cash Balance")
    opening_cash_balance: Optional[str] = Field(default=None, alias="Opening Cash Balance")

    contingent_liabilities: Optional[str] = Field(default=None, alias="Contingent Liabilities")
    creditors_outstanding_more_than_one_year: Optional[str] = Field(default=None, alias="Creditors Outstanding More Than One Year")
    debtors_outstanding_more_than_one_year: Optional[str] = Field(default=None, alias="Debtors Outstanding More Than One Year")
    inventory_outstanding_more_than_180_days: Optional[str] = Field(default=None, alias="Inventory Outstanding More Than 180 Days")
    disputed_trade_receivables: Optional[str] = Field(default=None, alias="Disputed Trade Receivables")
    advance_from_customers: Optional[str] = Field(default=None, alias="Advance From Customers")
    auditors_remuneration: Optional[str] = Field(default=None, alias="Auditors Remuneration")
    power_and_fuel_expenses: Optional[str] = Field(default=None, alias="Power and fuel expenses")
    significant_impairment: Optional[str] = Field(default=None, alias="Significant Impairment")
    one_time_revenue: Optional[str] = Field(default=None, alias="One-time Revenue")
    provision_for_doubtful_debts: Optional[str] = Field(default=None, alias="Provision for doubtful debts")
    bad_debts: Optional[str] = Field(default=None, alias="Bad Debts")
    related_party_investments: Optional[str] = Field(default=None, alias="Related Party Investments")
    related_party_expenses: Optional[str] = Field(default=None, alias="Related Party Expenses")
    related_party_revenues: Optional[str] = Field(default=None, alias="Related Party Revenues")
    related_party_loans_and_advances: Optional[str] = Field(default=None, alias="Related Party Loans and Advances")
    related_party_bad_debts: Optional[str] = Field(default=None, alias="Related Party Bad Debts")
    related_party_loan_liability: Optional[str] = Field(default=None, alias="Related Party Loan Liability")
    current_maturities_of_borrowings: Optional[str] = Field(default=None, alias="Current maturities of borrowings")

    risk_factors: Optional[str] = Field(default=None, alias="Risk Factors")
    business_segments: Optional[str] = Field(default=None, alias="Business Segments")
    currency: Optional[str] = Field(default=None, alias="Currency")
    country: Optional[str] = Field(default=None, alias="Country")
    ceo: Optional[str] = Field(default=None, alias="CEO")
    employees: Optional[str] = Field(default=None, alias="Employees")
    auditor: Optional[str] = Field(default=None, alias="Auditor")
    dividend: Optional[str] = Field(default=None, alias="Dividend")
    shares_outstanding: Optional[str] = Field(default=None, alias="Shares Outstanding")
    market_capitalization: Optional[str] = Field(default=None, alias="Market Capitalization")
    notes: Optional[str] = Field(default=None, alias="Notes")

    class Config:
        populate_by_name = True
        allow_population_by_field_name = True
