"""
valuation.py - CCM valuation core (pure, deterministic, stdlib only).
"""

from statistics import median, mean, pstdev


def _rng(value):
    """Concluded value -> (low, mid, high) at +/- 5%."""
    if value is None:
        return None, None, None
    return round(value * 0.95, 2), round(value, 2), round(value * 1.05, 2)


def _multiple_field(matrix):
    return {"EV/Revenue": "ev_revenue", "EV/EBITDA": "ev_ebitda",
            "P/E": "pe"}[matrix]


def _driver(subject, matrix):
    return {"EV/Revenue": subject.get("revenue"),
            "EV/EBITDA": subject.get("ebitda"),
            "P/E": subject.get("pat")}[matrix]


def multiple_summary(comparables, matrix):
    """Per-company multiples for the chosen matrix, plus median and average."""
    field = _multiple_field(matrix)
    rows, vals = [], []
    for c in comparables:
        v = c.get(field)
        rows.append({"name": c["name"], "multiple": v})
        if v is not None:
            vals.append(v)
    disp, spread_flag = None, "n/a"
    if len(vals) >= 2 and mean(vals):
        cv = pstdev(vals) / mean(vals)
        disp = round(cv, 3)
        spread_flag = "tight" if cv <= 0.20 else ("moderate" if cv <= 0.40 else "wide")
    return {
        "matrix": matrix,
        "companies": rows,
        "median": round(median(vals), 3) if vals else None,
        "average": round(mean(vals), 3) if vals else None,
        "min": round(min(vals), 3) if vals else None,
        "max": round(max(vals), 3) if vals else None,
        "dispersion_cv": disp,
        "dispersion": spread_flag,
        "n": len(vals),
    }


def nav_value(subject):
    """Net Asset Value = net worth adjusted for stated surplus items."""
    nw = subject.get("net_worth")
    if nw is None:
        return {"method": "NAV", "status": "missing_net_worth",
                "low": None, "mid": None, "high": None}
    non_op = ((subject.get("surplus_investments") or 0.0)
              + (subject.get("surplus_assets") or 0.0)
              - (subject.get("surplus_liabilities") or 0.0))
    nav = nw + non_op
    low, mid, high = _rng(nav)
    return {"method": "NAV", "status": "ok",
            "net_worth": nw, "non_operating_adjustment": round(non_op, 2),
            "nav": round(nav, 2), "low": low, "mid": mid, "high": high}


def ccm_value(subject, comparables, matrix):
    """Comparable Companies Method on the median multiple of the given matrix."""
    summ = multiple_summary(comparables, matrix)
    med = summ["median"]
    driver = _driver(subject, matrix)
    out = {"method": "CCM", "matrix": matrix, "multiple_summary": summ,
           "median_multiple": med, "driver": driver}

    # Robustness gates
    if summ["n"] < 2:
        out.update(status="insufficient_comparables", low=None, mid=None, high=None,
                   message=f"only {summ['n']} comparable(s) have a published "
                           f"{matrix} multiple - median needs at least 2; widen "
                           f"the screening or pick another matrix/sub-sector")
        return out
    if med is None:
        out.update(status="no_multiples", low=None, mid=None, high=None,
                   message=f"no comparable has a published {matrix} multiple")
        return out
    if driver is None:
        dl = {"EV/Revenue": "revenue", "EV/EBITDA": "EBITDA", "P/E": "PAT"}[matrix]
        out.update(status="missing_driver", low=None, mid=None, high=None,
                   message=f"{matrix} needs the subject's {dl}")
        return out
    if driver <= 0:
        dl = {"EV/Revenue": "revenue", "EV/EBITDA": "EBITDA", "P/E": "PAT"}[matrix]
        out.update(status="non_positive_driver", low=None, mid=None, high=None,
                   message=f"the {matrix} method cannot be applied when the "
                           f"subject's {dl} is not positive ({driver}); choose a "
                           f"different matrix")
        return out

    net_debt = ((subject.get("debt") or 0.0)
                + (subject.get("lease_liabilities") or 0.0)
                - (subject.get("cash") or 0.0))
    non_op = ((subject.get("surplus_investments") or 0.0)
              + (subject.get("surplus_assets") or 0.0)
              - (subject.get("surplus_liabilities") or 0.0))

    if matrix == "P/E":
        equity = med * driver + non_op
        ev = None
    else:
        ev = med * driver
        equity = ev - net_debt + non_op

    low, mid, high = _rng(equity)
    out.update(status="ok",
               enterprise_value=round(ev, 2) if ev is not None else None,
               net_debt=round(net_debt, 2), non_operating_adjustment=round(non_op, 2),
               equity_value=round(equity, 2), low=low, mid=mid, high=high)
    return out


CAVEATS = [
    "The valuation has been generated by an automated software tool and not by "
    "Deloitte professionals.",
    "Financial and market data are sourced directly from external databases "
    "without manual intervention by Deloitte.",
    "Comparable companies are identified based on database classifications and "
    "statistical mapping using the criteria selected by the user.",
    "Certain valuation adjustments, discounts, or premiums that may be relevant "
    "in specific circumstances have not been considered in the valuation.",
    "The valuation output does not constitute a Deloitte opinion, "
    "recommendation, or professional valuation report.",
]


def value(subject, comparables, matrix):
    """Full result: NAV + CCM (on the chosen matrix) + caveats. Deterministic."""
    return {
        "subject": subject,
        "matrix": matrix,
        "nav": nav_value(subject),
        "ccm": ccm_value(subject, comparables, matrix),
        "caveats": CAVEATS,
    }
