"""
Orchestrator: name/code -> resolve -> target -> peers -> valuation -> result.
The same entry point serves a listed company (financials from the DB) and a
private company (financials supplied by the user or the VLM extractor).
"""
from __future__ import annotations

from typing import Optional

from .. import db
from . import peers as peers_mod
from . import valuation as val_mod
from .model import Target, from_row, load_target, resolve

CAVEATS = [
    "Indicative screening valuation generated by an automated tool — not a "
    "Deloitte opinion or a certified valuation.",
    "Comparable multiples are real published Capitaline figures used as-is; "
    "no multiple is recomputed or fabricated.",
    "Comparable-company valuation on heterogeneous Indian companies carries "
    "wide inherent dispersion; treat the range, not a single point, as the answer.",
    "Where net debt (borrowings and cash) is unknown, equity is withheld and "
    "only the enterprise-value range is reported.",
]


def evaluate(conn, target: Target, *, max_peers: int = 8,
             filters: Optional[dict] = None) -> dict:
    disc = peers_mod.discover(conn, target, max_peers=max_peers, filters=filters)
    peers = disc["peers"]
    if len(peers) < 3:
        return {
            "status": "insufficient_peers",
            "target": target.to_dict(),
            "peers": peers, "peer_discovery": disc,
            "message": f"only {len(peers)} comparable(s) found in {target.sector}",
            "caveats": CAVEATS,
        }
    valuation = val_mod.value(target, peers)
    return {
        "status": "ok",
        "target": target.to_dict(),
        "peer_discovery": {k: v for k, v in disc.items() if k != "peers"},
        "peers": peers,
        "valuation": valuation,
        "caveats": CAVEATS,
    }


def evaluate_by_code(conn, code: int, **kw) -> dict:
    target = load_target(conn, code)
    if not target:
        return {"status": "no_match", "message": f"code {code} not found"}
    return evaluate(conn, target, **kw)


def evaluate_by_name(conn, name: str, **kw) -> dict:
    hits = resolve(conn, name)
    if not hits:
        return {"status": "no_match", "message": f"no company matches '{name}'"}
    return evaluate_by_code(conn, hits[0]["code"], **kw)
